using System.Data;
using System.Data.Common;
using KnowledgeTracker.Application.Knowledge;
using KnowledgeTracker.Data.Database;
using KnowledgeTracker.Domain.Knowledge;

namespace KnowledgeTracker.Data.Knowledge.Repositories;

public sealed class SqlServerTopicRepository(Func<DbConnection> connectionFactory, CurrentWorkspaceDataScope dataScope) : ITopicRepository
{
    public async Task<Topic?> FindAsync(Guid id, CancellationToken ct) { await using var connection = connectionFactory(); await connection.OpenAsync(ct); await using var command = connection.CreateCommand(); command.CommandText = "SELECT topic.Id, topic.SubjectId, topic.Name FROM dbo.Topics AS topic INNER JOIN dbo.Subjects AS subject ON subject.Id = topic.SubjectId WHERE topic.Id = @Id AND subject.UserId = @UserId AND subject.WorkspaceId = @WorkspaceId;"; command.AddParameter("@Id", DbType.Guid, id); AddScope(command); await using var reader = await command.ExecuteReaderAsync(ct); return await reader.ReadAsync(ct) ? new(reader.GetGuid(0), reader.GetGuid(1), reader.GetString(2)) : null; }
    public async Task<IReadOnlyCollection<Topic>> ListAsync(CancellationToken ct) { await using var connection = connectionFactory(); await connection.OpenAsync(ct); await using var command = connection.CreateCommand(); command.CommandText = "SELECT topic.Id, topic.SubjectId, topic.Name FROM dbo.Topics AS topic INNER JOIN dbo.Subjects AS subject ON subject.Id = topic.SubjectId WHERE subject.UserId = @UserId AND subject.WorkspaceId = @WorkspaceId ORDER BY topic.SubjectId, topic.Name, topic.Id;"; AddScope(command); await using var reader = await command.ExecuteReaderAsync(ct); var result = new List<Topic>(); while (await reader.ReadAsync(ct)) result.Add(new(reader.GetGuid(0), reader.GetGuid(1), reader.GetString(2))); return result; }
    public async Task AddAsync(Topic topic, CancellationToken ct) { await using var connection = connectionFactory(); await connection.OpenAsync(ct); await using var command = connection.CreateCommand(); command.CommandText = "INSERT INTO dbo.Topics (Id, SubjectId, Name) SELECT @Id, @SubjectId, @Name WHERE EXISTS (SELECT 1 FROM dbo.Subjects WHERE Id = @SubjectId AND UserId = @UserId AND WorkspaceId = @WorkspaceId);"; Add(command, topic); AddScope(command); await command.ExecuteNonQueryAsync(ct); }
    public async Task UpdateAsync(Topic topic, CancellationToken ct) { await using var connection = connectionFactory(); await connection.OpenAsync(ct); await using var command = connection.CreateCommand(); command.CommandText = "UPDATE topic SET Name = @Name FROM dbo.Topics AS topic INNER JOIN dbo.Subjects AS subject ON subject.Id = topic.SubjectId WHERE topic.Id = @Id AND subject.UserId = @UserId AND subject.WorkspaceId = @WorkspaceId;"; Add(command, topic); AddScope(command); await command.ExecuteNonQueryAsync(ct); }
    public async Task<bool> IsInUseAsync(Guid id, CancellationToken ct) { await using var connection = connectionFactory(); await connection.OpenAsync(ct); await using var command = connection.CreateCommand(); command.CommandText = "SELECT CASE WHEN EXISTS (SELECT 1 FROM dbo.Topics AS topic INNER JOIN dbo.Subjects AS subject ON subject.Id = topic.SubjectId WHERE topic.Id = @Id AND subject.UserId = @UserId AND subject.WorkspaceId = @WorkspaceId AND (EXISTS (SELECT 1 FROM dbo.StudyNotes WHERE TopicId = topic.Id) OR EXISTS (SELECT 1 FROM dbo.SubjectGoals WHERE TopicId = topic.Id))) THEN 1 ELSE 0 END;"; command.AddParameter("@Id", DbType.Guid, id); AddScope(command); return Convert.ToBoolean(await command.ExecuteScalarAsync(ct)); }
    public async Task<bool> DeleteAsync(Guid id, CancellationToken ct) { await using var connection = connectionFactory(); await connection.OpenAsync(ct); await using var command = connection.CreateCommand(); command.CommandText = "DELETE topic FROM dbo.Topics AS topic INNER JOIN dbo.Subjects AS subject ON subject.Id = topic.SubjectId WHERE topic.Id = @Id AND subject.UserId = @UserId AND subject.WorkspaceId = @WorkspaceId;"; command.AddParameter("@Id", DbType.Guid, id); AddScope(command); return await command.ExecuteNonQueryAsync(ct) > 0; }
    private static void Add(DbCommand command, Topic topic) { command.AddParameter("@Id", DbType.Guid, topic.Id); command.AddParameter("@SubjectId", DbType.Guid, topic.SubjectId); command.AddParameter("@Name", DbType.String, topic.Name); }
    private void AddScope(DbCommand command) { command.AddParameter("@UserId", DbType.Guid, dataScope.RequireUserId()); command.AddParameter("@WorkspaceId", DbType.Guid, dataScope.RequireWorkspaceId()); }
}
